[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "crates/mlaa",
    "crates/mlaa_egui",
    "crates/mlaa_image",
]

[workspace.dependencies]
mlaa = { path = "crates/mlaa" }
