[package]
name    = "mlaa_impl"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
default = []
serde   = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }
